### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by Phil1988** [nsiatras/rsdoc-to-sab-converter#1]
I have a .rsdoc file, DSM 2.0 and Windows 7 with java installed.
how to execute your program/addon?

**Comment by pietrek999** [comment]
Hello !!!
I have been able to convert the rsdoc file to sab
but I can not run it.
Here's what pops up in the report window:

Importing: C:/Users/user/Desktop/designspark/Projekt.sab
Reading: C:\Users\user\Desktop\designspark\Projekt.sab
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\AppData\Roaming\FreeCAD\Mod\InventorLoader-master\importerIL.py", line 78, in insert
    open(filename, skip, only, root)
  File "C:\Users\user\AppData\Roaming\FreeCAD\Mod\InventorLoader-master\importerIL.py", line 91, in open
    reader = read(doc, filename, True)
  File "C:\Users\user\AppData\Roaming\FreeCAD\Mod\InventorLoader-master\importerIL.py", line 43, in read
    if (importerSAT.readBinary(doc, filename)):
  File "C:\Users\user\AppData\Roaming\FreeCAD\Mod\InventorLoader-master\importerSAT.py", line 446, in readBinary
    header.readBinary(data)
  File "C:\Users\user\AppData\Roaming\FreeCAD\Mod\InventorLoader-master\importerSAT.py", line 175, in readBinary
    tag, self.version, i = readNextSabChunk(data, 0)
  File "C:\Users\user\AppData\Roaming\FreeCAD\Mod\InventorLoader-master\Acis.py", line 3939, in readNextSabChunk
    raise Exception("Don't know to read TAG %X" %(tag))
<type 'exceptions.Exception'>: Don't know to read TAG 41

**Comment by Phil1988** [comment]
I didnt get it working, so I used this:
https://github.com/arekm/rsdoc-to-sat/issues/2
